authorName: default
experimentName: logical_form
trialConcurrency: 4
maxExecDuration: 30m
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: nni_search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
# The path and the running command of trial
trial:
  command: python nni_main.py --cuda_device=2 --language funql --train_data ./data/geo/geo_funql_train.tsv --test_data ./data/geo/geo_funql_test.tsv --basepath ./trained_models/geo/tune_funql/
  codeDir: .
  gpuNum: 1
